sass:	
	pysassc -t expanded scss/Dracula.scss themes/Dracula.theme
	pysassc -t expanded scss/One-Dark.scss themes/One-Dark.theme
	pysassc -t expanded scss/System-Dark.scss themes/System-Dark.theme
	pysassc -t expanded scss/System-Light.scss themes/System-Light.theme
	
.PHONY: sass
